apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus
    app.kubernetes.io/part-of: test-app-167084296
  name: java-quarkus
  namespace: zsv69g1w
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: java-quarkus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: java-quarkus
    spec:
      containers:
      - env:
        - name: secondEnvVar
          value: "3000"
        image: quay.io/redhat-appstudio/user-workload:zsv69g1w-java-quarkus
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 11m
            memory: 1Gi
status: {}
